### ISSUE TITLE
Make sure to handle deleted tombstones the right way with Syncto

### ISSUE THREAD

**Issue by Natim** [mozilla-services/syncto#13]

**Comment by Natim** [comment]
As far as I can tell, there are no trace of tombstones in the Sync documentation and during my investigation I didn't get any when fetching the collection with or without a newer parameter.

I will send a mail to @rnewman to confirm this assumption but I suppose I may have to store tombstones on Syncto side which is not really a good news.

**Comment by rnewman** [comment]
A deletion in Sync is an encrypted record like any other. The payload will be {deleted: true}.

**Comment by rnewman** [comment]
Deletion of a record (blanking the server, for example) and deleting an item are different things. Absence does not imply deletion.

**Comment by Natim** [comment]
> A deletion in Sync is an encrypted record like any other.

Since it is encrypted, the only way for us to detect it is that they don't have any `sortindex` unencrypted param left.

@rnewman do you know if this tombstones are deleted at some point by clients or just ignored if present? If yes on which strategy?

**Comment by michielbdejong** [comment]
Sorry, I missed this discussion, because I wasn't (until now) watching this github repo.

As discussed on irc, I would envision the Kinto.js collection to contain an exact copy of all the remote records with their id's and their payloads, just decrypted, and the interpretation of those payloads is left to the DataAdapters inside the Sync app.

So it's easiest if we leave this role of dealing with the semantics of `{ deleted: true }` payloads to the DataAdapters, and both Syncto and Kinto.js treat such records just like they would treat any other record.

**Comment by Natim** [comment]
This means we cannot remove records from the Kinto.js layer ever.

**Comment by rnewman** [comment]
Indeed. Note also that deleted records do have a sortindex; deletion is an engine-specific payload content attribute, so even with cleartext there's nothing the server can/should do beyond obeying the TTL.
