### ISSUE TITLE
Investigate onboarding user flow

### ISSUE THREAD

**Issue by Natim** [mozilla-services/syncto#22]
If a user first connects on Firefox Sync through Syncto, we want to assign him a new Sync node and setup the token server accordingly.

We need to investigate how this works.

**Comment by michielbdejong** [comment]
I think the ['first act'](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol#creating-the-account) needs to be done by FxOS talking directly to fxa-auth-server, to preserve end-to-end encryption (we don't want Syncto to see the user's FxA password).

This is not planned for 2.5 though; if users try to onboard from their phone, we will just display an error message saying "Please sync from Firefox Desktop first, and then try again".

But once it's working, I think the call to `/account/create` will be enough (including assigning the Sync node?), and an FxOS client will just do a PUT to crypto/keys to initialize the account with the bulk key bundle it generated. So I don't think there will be any special things to do for Syncto, but I could be wrong.

**Comment by Natim** [comment]
> I think the 'first act' needs to be done by FxOS talking directly to fxa-auth-server,

Yes but this is about Firefox Account creation not Firefox Sync setup. I was talking about the latter.

> I think the call to /account/create will be enough (including assigning the Sync node?)

I have to figure out how is the Sync node assigned to an existing user. If it is automatic on the first call to the token server then there are nothing to do on our side.

> A FxOS client will just do a PUT to crypto/keys to initialize the account with the bulk key bundle it generated.

Apart from detecting that keys are missing and generate them.

Does @rnewman can validate that we are right here?
- Will a call to the token server from a new user assign a Sync node?
- Should a client generate and PUT new keys on a sync server if there are not present?

**Comment by rnewman** [comment]
I'll be AFK for most or all of today, but I'll comment on this as soon as I
can.

**Comment by rnewman** [comment]
OK, answers to your questions.

The token server is responsible for taking an assertion and a client state — `X-Client-State`, derived from `kB` — and returning an `api_endpoint` and a token to use with it.

The API endpoint (Sync server) might be new or it might be a previous one. It might be the same physical server but with a different UID. The client doesn't care.

X-C-S is there to make sure that a client with a new sync key (e.g., after a password change) never ends up at the same server+uid combination; this avoids some classes of data integrity bugs.

Populating a blank server is an involved and slightly risky business.

There are a few definitions of 'blank':
- Missing everything.
- Missing data, but has `m/g` and `c/k`.
- Missing `c/k`, but has `m/g`.
- Potentially: missing `m/g` but has other stuff.

There are two ways of detecting 'blank':
- Not present in `info/collections`.
- 404 on fetch.
- Record fetches, but is malformed or encrypted with the wrong key.

A client needs to get the server into a consistent state, which might involve wiping `/storage/` in order to e.g., delete data that might be encrypted with a lost key.

The client needs to make sure that the server ends up with four things:
- A meta/global with the right engine selections and declined list.
- A `crypto/keys` object, encrypted with the correct `kB`, containing a (new, I think) bulk key bundle.
- Our encrypted client record.
- Collection data encrypted with the right keys from the bulk key bundle. This might take some time to upload.

The reason this is tricky: doing this involves 4+ HTTP requests, including potentially very slow bulk deletions, and clients need to be careful to avoid races. For example, two clients might race with meta/global, leading to a collection being written without having an engine entry, and two clients might race with key upload, leading to collection data being encrypted with the wrong bulk keys (eek!).

`X-If-Unmodified-Since` and careful re-fetches is the right approach. It's not as simple as "oh, it's an empty server, I'll run four `PUT`s".

The above is a fairly complete picture of what's supposed to happen, but I recommend you read the Android Sync source, and maybe the desktop `service.js` code to get more angles.

**Comment by Natim** [comment]
Thanks a lot for this useful information.

**Comment by rfk** [comment]
>  If it is automatic on the first call to the token server then there are nothing to do on our side.

From the tokenserver's perspective, yes, it's automatic the first time the user shows up and asks for a node.  As @rnewman points out, there's a not of extra setup to do on the node itself, but the allocation of a user to a node is automatic and transparent.

**Comment by Natim** [comment]
Thank you guys, we have all the information needed for now.
